
version: "3.5"

networks:
  b0:
    driver: bridge

services:
  node:
    build:
      context: ./
      dockerfile: ./u18-dockerfile
    image: u18
    volumes:
      - type: bind
        source: .
        target: /work
    networks:
      - b0

